//export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOAD_INFO_REQUESTED = 'LOAD_INFO_REQUESTED'
export const LOAD_INFO_OK = 'LOAD_INFO_OK'
export const LOAD_INFO_FAIL = 'LOAD_INFO_FAIL'